elasticsearch:
  clusterNodes: 26.6.0.95:9300
  clusterName: paic-elasticsearch

curator:
  retryCount: 5
  elapsedTimeMs: 5000
  connectString: cnsz033391,cnsz033392,cnsz033393,cnsz033394,cnsz033398
  sessionTimeoutMs: 5000
  connectionTimeoutMs: 5000
  rootPath: /es_offline
server:
  port: 0
workDir:
  /data/data01/es_offline,/data/data02/es_offline,/data/data03/es_offline,/data/data04/es_offline,/data/data05/es_offline,/data/data06/es_offline,/data/data07/es_offline,/data/data08/es_offline,/data/data09/es_offline,/data/data10/es_offline,/data/data11/es_offline,/data/data12/es_offline
threadpools:
  process:
    corePoolSize: 8
    maxPoolSize: 8
  download:
    corePoolSize: 24
    maxPoolSize: 24