elasticsearch:
  clusterNodes: localhost:9300
  clusterName: elasticsearch

curator:
  retryCount: 5  #重试次数
  elapsedTimeMs: 5000   #重试间隔时间
  connectString: 127.0.0.1:2181   # zookeeper 地址
  sessionTimeoutMs: 60000  # session超时时间
  connectionTimeoutMs: 5000  # 连接超时时间
  rootPath: /es_offline
server:
  port: 0
workDir:
  /tmp/es_offline
threadpools:
  download:
    corePoolSize: 10
    maxPoolSize: 20
  process:
    corePoolSize: 20
    maxPoolSize: 20